name: Botgram shell-bot in GitHub Actions Ubuntu Runner

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-20.04

    env:
      GitHubMail: "flashokiller@gmail.com"
      GitHubName: "flashokiller"
      # GH_TOKEN >> Github Personal Access Token << In Repository Secrets
      # authToken >> Telegram Bot Token << In Repository Secrets
      # ownerID >> Telegram User/Admin owner ID << In Repository Secrets

    steps:
      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global color.ui true
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      - name: Cleanup Workspace
        uses: rokibhasansagar/slimhub_actions@main

      - name: wew
        run: |
          git clone https://github.com/AndroidDumps/dumpyara dump
          cd dump
          apt update && apt upgrade
          bash setup.sh
      - name: test
        run: |
         bash dumpyara.sh "http://in-sysup-txdl.vivoglobal.com/upgrade/official/officialFiles/PD1928F_EX_A_1.70.5-update-full_1617846068.zip OR 1916" 
